
services:
  # Django バックエンドサービス
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    env_file:
      - .env.dev
    depends_on:
      db:
        condition: service_healthy # <-- ここを修正
    networks:
      - app_network

  # PostgreSQL データベースサービス
  db:
    image: postgres:13
    volumes:
      - pg_data:/var/lib/postgresql/data
    env_file:
      - .env.dev
    networks:
      - app_network
    healthcheck: # <-- このヘルスチェックを追加！
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s # 起動後10秒はチェックを待つ

  # React Native フロントエンドサービス
  frontend:
    # ... frontend サービスの設定は省略 (変更なし)
    build:
      context: ./frontend
      dockerfile: Dockerfile
    # 修正点: --tunnel オプションを追加して、Expo Goからアクセスできるようにします。
    # `npm run start` に引数を渡すために `sh -c "..."` と `--` を使います。
    command: sh -c "npm run start -- --tunnel"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "19000:19000"
      - "19001:19001"
      - "8081:8081"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  pg_data: