# Generated by Django 4.2.23 on 2025-07-27 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ramen_log', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ramenlog',
            name='soup_richness',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
